"""
This script simulates the opinion dynamics generated by using a discrete HK model.
A function HK_discrete is called after defining the required parameters.
The results are plotted on a 'Timesteps vs Opinions' figure.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from functions.HK_discrete import HK_discrete

# PARAMETERS
#----------------------------------------
# the number of agents
n = 20

# the bound
R = 0.15

# the stopping criterion
stop = 10**(-5)
#----------------------------------------


# INITIAL CONDITIONS
#----------------------------------------
# OPTION 1: simulate the initial opinions
# x0 = np.random.uniform(0, 1, n)
# x0.sort()

# OPTION 2: use expected value distribution
x0 = [i/(n+1) for i in range(1, n+1)]
#----------------------------------------

# SIMULATION
#----------------------------------------
res = HK_discrete (R, n, x0, stop, result = 'FULL', include_self = True)

# calculate the no of steps taken
steps = len(res)
#----------------------------------------

# PLOT THE RESULTS
#----------------------------------------
figure(figsize=(10, 8), dpi=80)

# define the colour map
colors = plt.cm.gist_rainbow(np.linspace(0, 1, n))

# plot each agent separately
for i in range(len(x0)):
    plt.plot(range(steps), res[:,i], color = colors[i])


plt.xlabel("Timesteps", fontsize = 14)
plt.ylabel("Opinions", fontsize = 14)
plt.title("Discrete-Time Opinion Dynamics", fontsize = 17)
plt.grid()
plt.show()
