"""
This script simulates the opinion dynamics generated by using an SDE version of HK model.
A function HK_sde is called after defining the required parameters.
The results are plotted on a 'Timesteps vs Opinions' figure.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import os
from functions.HK_sde import HK_sde
from functions.calc_order_par import calc_order_par

# set the seed
# np.random.seed(10)

# PARAMETERS
#----------------------------------------
# the number of agents
n = 100

# the bound
R = 0.086

# the stopping criterion
stop = 10**(-5)

# the step size
h = 0.05

# the number of steps
steps = 1000

# the noise level
sigma = 0.02

# the boundary condition: reflect/adsorb/period
bound_cond = 'adsorb'


# INITIAL CONDITIONS
#----------------------------------------
# OPTION 1: simulate the initial opinions
# x0 = np.random.uniform(0, 1, n)
# x0.sort()

# OPTION 2: use expected value distribution
x0 = [i/(n+1) for i in range(1, n+1)]


# SIMULATION
#----------------------------------------
res = HK_sde (R, n, x0, h, sigma, stop, result = 'FULL', include_self = True, max_steps = steps, bound_cond = bound_cond)

# calculate the no of steps taken
steps = len(res)
#----------------------------------------


# PLOT THE RESULTS
#----------------------------------------
figure(figsize=(10, 8), dpi=80)

# define the colour map
colors = plt.cm.gist_rainbow(np.linspace(0, 1, n))

# plot each agent separately
for i in range(n):
    plt.plot(range(steps), res[:,i], color = colors[i], linewidth = 0.7)

plt.xlabel("Timesteps")
plt.ylabel("Opinions")
plt.title("Opinion Dynamics with Radicals")
plt.grid()
plt.show()
