"""
This script simulates the 2D opinion dynamics generated by using an ODE HK model.
A function HK_ode_2d is called after defining the required parameters.
The results are plotted on a 'Opinions x vs Opinions y' figure with a few pathes illustrated.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from analysis_2D.functions.HK_sde_2d import HK_sde_2d
from analysis_2D.functions.calc_order_par import calc_order_par

# set seed
np.random.seed(27)

# PARAMETERS
#----------------------------------------

# the number of agents
n = 20

# the bound
R = 0.2

# the stopping criterion
stop = 10**(-5)

# the step size
h = 0.05

# the noise level
sigma = 0.01


#----------------------------------------

# INITIAL CONDITIONS
#----------------------------------------
# OPTION 1 - SQUARE: sample the initial opinions from a uniform distribution
# x0 = np.random.uniform(0, 1, n)
# y0 = np.random.uniform(0, 1, n)
#
# x = [[x0[i], y0[i]] for i in range(n)]


#----------------------------------------
# OPTION 2 - CIRCLE: sample the initial opinions from a uniform distribution
length = 0.5 * np.sqrt(np.random.uniform(0, 1, n))
angle = 2 * np.pi * np.random.uniform(0, 1, n)

x = []

x0 = 0.5 + length * np.cos(angle)
y0 = 0.5 + length * np.sin(angle)

x = [[x0[i], y0[i]] for i in range(n)]
#----------------------------------------

# SIMULATION
#----------------------------------------
res = HK_sde_2d (R, n, x, h,sigma, stop, result = 'FULL', max_steps = 2000, dist_norm = 1)

# calculate the no of steps taken
steps = len(res)
#----------------------------------------


# PLOT THE PATHS
#----------------------------------------
figure(figsize=(10, 8), dpi=80)

# define the colour map
colors = plt.cm.gist_rainbow(np.linspace(0, 1, n))
step_for_arrow = int(steps/2)

# plot each agent separately
for i in range(n):
    # add paths
    plt.plot(res[:,i,0], res[:,i,1], color = colors[i])
    # add arrows
    plt.arrow(res[step_for_arrow,i,0], res[step_for_arrow,i,1], res[step_for_arrow,i,0]-res[step_for_arrow-1,i,0], res[step_for_arrow,i,1]-res[step_for_arrow-1,i,1], lw=0, length_includes_head=True, head_width=.01, color = colors[i])

# plot each agent separately
for i in range(n):
    # add last state
    plt.plot(res[steps-1,i,0], res[steps-1,i,1], linestyle = "", marker = "o", markersize = 7, color = 'black')
Q = calc_order_par(res[-1], R, n, 'adsorb')
plt.xlabel("x1")
plt.ylabel("x2")
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.title("SDE Opinion Dynamics in 2D. Order Parameter: {}.".format(round(Q,4)))
plt.grid()
plt.gca().set_aspect('equal', adjustable='box')
plt.show()


# PLOT THE SNAPSHOTS (every 20th step)
#----------------------------------------
fig = plt.figure(figsize=(25, steps//(20*3)*10))
s = 1

for t in range(0, steps, 20):

    plt.subplot(steps//(20*3) + 1, 3, s)
    s = s + 1

    # plot each agent separately
    for i in range(n):
        plt.plot(res[t][:,0], res[t][:,1], linestyle = "", marker = "o", markersize = 7, color = 'purple')

    plt.xlabel("Opinions x1", fontsize = 14)
    plt.ylabel("Opinions x2", fontsize = 14)
    plt.xlim([-0.02,1.02])
    plt.ylim([-0.02,1.02])
    plt.title("t = {}".format(t), fontsize = 17)
    plt.grid()
    plt.gca().set_aspect('equal', adjustable='box')
plt.show()
